# Generated by Django 2.1.7 on 2019-03-12 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenseTracker', '0002_remove_expense_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='date',
        ),
    ]
