# Generated by Django 2.1.7 on 2019-03-07 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenseTracker', '0003_income'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='income',
            options={'verbose_name': 'Income', 'verbose_name_plural': 'All Incomes'},
        ),
    ]
