# Generated by Django 2.1.7 on 2019-03-08 06:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expenseTracker', '0004_auto_20190307_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('expense_type', models.CharField(choices=[('Fixed', 'Fixed'), ('Variable', 'Variable')], max_length=100)),
                ('amount', models.IntegerField()),
                ('note', models.TextField()),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'All Expenses',
            },
        ),
        migrations.AlterModelOptions(
            name='income',
            options={'verbose_name': 'Expense', 'verbose_name_plural': 'All Expenses'},
        ),
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenseTracker.Category'),
        ),
    ]
