# Generated by Django 2.1.7 on 2019-04-09 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenseTracker', '0004_auto_20190325_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='note',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='income',
            name='note',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
