# Generated by Django 2.1.7 on 2019-03-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenseTracker', '0006_auto_20190308_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='note',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='income',
            name='note',
            field=models.CharField(max_length=500),
        ),
    ]
