# Generated by Django 2.1.7 on 2019-04-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenseTracker', '0008_auto_20190411_1317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='type',
            new_name='category_type',
        ),
        migrations.AlterField(
            model_name='expense',
            name='note',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='note',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
